version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t   ddxplague/github-webhook-creator:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push ddxplague/github-webhook-creator:$TAG
